---
title: "git_00"
author: "Luis Resendez"
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
"Just the place for a Snark!" the Bellman cried,


   As he landed his crew with care;
   
   
Supporting each man on the top of the tide


   By a finger entwined in his hair.
   
   
   "Just the place for a Snark! I have said it twice:
   
   
   That alone should encourage the crew.
   
   
Just the place for a Snark! I have said it thrice:


   What I tell you three times is true."<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
He halted in the wind, and - what was that


Far in the maples, pale, but not a ghost?


He stood there bringing March against his thought,


And yet too ready to believe the most.


"Oh, that's the Paradise-in-bloom," I said;


And truly it was fair enough for flowers


had we but in us to assume in march


Such white luxuriance of May for ours.


We stood a moment so in a strange world,


Myself as one his own pretense deceives;


And then I said the truth (and we moved on).


A young beech clinging to its last year's leaves.
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
"The sun was shining on the sea,


Shining with all his might
      
      
He did his very best to make


The billows smooth and bright
      
      
And this was odd, because it was


The middle of the night.
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
God comes to us in quiet and simple ways.


He is there when the breeze rustles the palm fronds on a quiet, lazy, sunny afternoon.


When the raindrops softly patter on the thirsty tin roofs of the poor, he is there.


Look for him behind the laughing eyes of a child,


or smell him in blossoming jasmine flowers


on a clear and starry moonlit night.


Hold his hand when you take your love by the hand,


and feel the warmth of his tears


as you console a grieving friend in your arms. 


He is there in a baby's first cry


and in the dying man's last sigh.


When the waves break on the golden sands


and the seagulls fly into the white clouds,


when the church bells ring on an Easter Sunday


inviting you to receive the sacred brad, he is there.


Taste him when you bite into the yellow ripeness of a mango


or when you quench your thirst with sweet water of a coconut.


God comes to us only in quiet and simple ways.


Never his presence in violence will you find;


never look for him in words of anger or cowardly actions.


His love and his peace surround us, above and beyond.


And only in those simple, everyday things


when we look with our eyes filled with his love


can we find him.

<!--Put a short poem of your choice 8-20 lines,here!-->
